### PR TITLE
meta/Fedora: Introduce SELinux policy

### PR DESCRIPTION
**Pull request by tylerjwatson**
This simple patch introduces support for an SELinux module which grants `qemu` enough permissions to read/write socket files in `/tmp` created by `ivshmem-server`, allowing for qemu to start successfully in fedora or distributions which have enough policy to ship in enforcing.

The policy is in a `contrib/redhat` directory to be featured inside a `%policy` section of an RPM specfile which will come once the build structure settles down a bit.  It might be done by me or a more experienced packager.

Install the policy with `semodule -i contrib/redhat/qemu-ivshmem-sock.pp`. A LookingGlass enabled virtual machine will now start as normal without compromising security.

### CODE REVIEW

**Comment by gnif** [comment]
Looks good, thanks! Re base and get rid of that merge and ill throw it in :D

**Comment by jonpas** [comment]
_You probably knew this, but just in case: https://i.imgur.com/lMUv26e.png_
Keep up the good work everyone!

**Comment by gnif** [comment]
@jonpas no I didn't, thanks!

**Comment by jonpas** [comment]
Than I am glad I was of help! :)

**Comment by tylerjwatson** [comment]
Whoa, I didn't realise that either.  You did me a learn @jonpas.

**Pull request merged**
