### PR TITLE
Libvirt docs touchup

### PR DESCRIPTION
**Pull request by majcosta**
if accepted, please squash

### CODE REVIEW

**Comment by majcosta** [comment]
Rationale:
image

**Comment by gnif** [comment]
Looks good  but please squash these two commits into one and use the naming convention for commits on this project, ie:

`[doc] kvmfr/libvirt: change double quotes to single quotes`

Also be sure to add yourself to the `AUTHORS` file

**Review by JJRcop — APPROVED** [review]

**Comment by gnif** [comment]
@JJRcop until the issues I raised are addressed this still needs work.

**Comment by JJRcop** [comment]
Because you're using the GitHub website to make these changes, unless you download [Git](https://git-scm.com) onto your computer (or a [GUI client](https://git-scm.com/downloads/guis/)), you cannot complete the changes requested and will have to [start over](https://github.com/gnif/LookingGlass/edit/master/doc/ivshmem_kvmfr.rst) with a new Pull Request, keeping in mind to name your commit following our naming convention as noted.

You may want to [use github.dev](https://github.dev/gnif/LookingGlass/blob/master/doc/ivshmem_kvmfr.rst) to start over. It's it's an online VS code editor made by GitHub that lets you easily edit 2 or more files in the same commit.

Otherwise, we won't make these changes for you. We recommend downloading a git client for best results especially if you plan to continue contributing to open source projects like Looking Glass in the future.

**Comment by JJRcop** [comment]
@majcosta Because you're using the GitHub website to make these changes, unless you download [Git](https://git-scm.com) onto your computer (or a [GUI client](https://git-scm.com/downloads/guis/)), you cannot complete the changes requested and will have to [start over](https://github.com/gnif/LookingGlass/edit/master/doc/ivshmem_kvmfr.rst) with a new Pull Request, keeping in mind to name your commit following our naming convention as noted.

You may want to [use github.dev](https://github.dev/gnif/LookingGlass/blob/master/doc/ivshmem_kvmfr.rst) to start over. It's an online VS code editor made by GitHub that lets you easily edit 2 or more files in the same commit.

Otherwise, we won't make these changes for you. We recommend downloading a git client for best results especially if you plan to continue contributing to open source projects like Looking Glass in the future.

**Comment by majcosta** [comment]
ok, done

**Pull request merged**
