### PR TITLE
[client] egl/imgui: use imgui for night vision gain configuration

### PR DESCRIPTION
**Pull request by quantum5**

### CODE REVIEW

**Comment by gnif** [comment]
Sorry but this is something that is toggled frequently in titles that have a day/night cycle, this needs to stay on a keybind.

**Comment by quantum5** [comment]
Do you want to have it in the config dialog as well or just have the keybind?

**Comment by gnif** [comment]
Doesn't hurt to have both I guess

**Comment by quantum5** [comment]
Done.

**Pull request merged**
