### PR TITLE
Fix -Werror=maybe-uninitialized

### PR DESCRIPTION
**Pull request by luqasz**

### CODE REVIEW

**Comment by gnif** [comment]
Which compiler/version is this occurring on? and please share your compile flags. I can't trigger this false positive.

**Comment by luqasz** [comment]
```gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Triggers with `-DCMAKE_BUILD_TYPE:STRING=Release`

**Comment by gnif** [comment]
Please show how GCC is being invoked on this file, you can obtain this by running:
`VERBOSE=1 make`

**Comment by luqasz** [comment]
```[72/85] /usr/bin/cc  -I../include -Iinclude -I/usr/include/SDL2 -I../renderers/EGL/src -Irenderers/EGL/shader -I/home/lkostka/workspace/LookingGlass/common/include -I../fonts/SDL/include -O3 -DNDEBUG   -D ATOMIC_LOCKING -D GL_GLEXT_PROTOTYPES -march=native -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wimplicit-fallthrough=2 -Werror -Wfatal-errors -ffast-math -fdata-sections -ffunction-sections -std=gnu11 -MD -MT renderers/EGL/CMakeFiles/renderer_EGL.dir/egl.c.o -MF renderers/EGL/CMakeFiles/renderer_EGL.dir/egl.c.o.d -o renderers/EGL/CMakeFiles/renderer_EGL.dir/egl.c.o   -c ../renderers/EGL/egl.c
FAILED: renderers/EGL/CMakeFiles/renderer_EGL.dir/egl.c.o 
/usr/bin/cc  -I../include -Iinclude -I/usr/include/SDL2 -I../renderers/EGL/src -Irenderers/EGL/shader -I/home/lkostka/workspace/LookingGlass/common/include -I../fonts/SDL/include -O3 -DNDEBUG   -D ATOMIC_LOCKING -D GL_GLEXT_PROTOTYPES -march=native -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wimplicit-fallthrough=2 -Werror -Wfatal-errors -ffast-math -fdata-sections -ffunction-sections -std=gnu11 -MD -MT renderers/EGL/CMakeFiles/renderer_EGL.dir/egl.c.o -MF renderers/EGL/CMakeFiles/renderer_EGL.dir/egl.c.o.d -o renderers/EGL/CMakeFiles/renderer_EGL.dir/egl.c.o   -c ../renderers/EGL/egl.c
../renderers/EGL/egl.c: In function ‘egl_calc_mouse_size’:
../renderers/EGL/egl.c:274:10: error: ‘h’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  274 |   int w, h;
      |          ^
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors
```

**Pull request closed without merging**
