### PR TITLE
Build package on debian/ubuntu

### PR DESCRIPTION
**Pull request by luqasz**
Patch allows building native deb packages on debian, ubuntu. Just run 
dpkg-buildpackage -B --no-sign -jauto

Packages required to build:
* build-essential
* clang / gcc

### CODE REVIEW

**Comment by luqasz** [comment]
As for package hosting:
* https://packagecloud.io/pricing
* https://bintray.com/account/pricing?tab=account&type=pricing

Both have free open source plans.
I do also maintain my collection of `deb` packages with aptly so feel free if this is and option for you.

**Comment by gnif** [comment]
As per request from the Debian team we do not include the `debian` build directory intentionally otherwise it makes it hard for the package maintainer to maintain the package. Your change to the cmake however is acceptable if you were to provide this as a separate patch.

**Comment by luqasz** [comment]
> As per request from the Debian team we do not include the debian build directory intentionally otherwise it makes it hard for the package maintainer to maintain the package.

I didn't know that deban already have this [packaged](https://tracker.debian.org/pkg/looking-glass).

**Comment by gnif** [comment]
No worries, thanks :)

**Pull request closed without merging**
