### PR TITLE
[client] mouse: update cursor draw state even when not in focus

### PR DESCRIPTION
**Pull request by Xyene**
Previously, the cursor would be set to a hidden state when the Looking
Glass window did not have focus, even if the pointer was above the
window, and the window was receiving pointer events (and passed them to
the guest).

### CODE REVIEW

**Comment by gnif** [comment]
This is a UX issue more than anything.

It's correct that the pointer is hidden because people running LG maximized but not fullscreen expect the guest cursor to allow them to exit the client window onto another window that may be partially obscuring the LG window. As the guest and local cursors may not be aligned it is very confusing/jarring when it happens.

**Comment by Xyene** [comment]
> This is a UX issue more than anything.

> As the guest and local cursors may not be aligned it is very confusing/jarring when it happens.

I can see this being the case. I use the 1:1 registry hack and this behavior changed as part of the refactors yesterday.

However, in this case I think the expectation would be that:

- the host cursor isn't hidden when LG doesn't have focus (it currently is, so there's just no cursor displayed over the LG window)
- LG doesn't pass events to the guest when it doesn't have focus (it currently does, so you have on-hover events triggering in the guest despite not seeing the cursor)
- the cursor is shown when the LG window regains focus (it currently isn't)

**Comment by gnif** [comment]
> the host cursor isn't hidden when LG doesn't have focus (it currently is, so there's just no cursor displayed over the LG window)

under Xorg this is not the case, just tested and verified.

> LG doesn't pass events to the guest when it doesn't have focus (it currently does, so you have on-hover events triggering in the guest despite not seeing the cursor)

I just patched this, but yet to push it.

> the cursor is shown when the LG window regains focus (it currently isn't)

Agreed, working on this now.

**Comment by gnif** [comment]
This should all now be addressed in the current master, can you please re-test?

**Pull request closed without merging**
