### PR TITLE
[host] nvfbc: Fix dwmapi linking error

### PR DESCRIPTION
**Pull request by 8BallBomBom**
Fixed linking for DwmFlush and also rearranged as per how DXGI is.

### CODE REVIEW

**Comment by gnif** [comment]
Thanks but you also need to add yourself to the AUTHORS file before this can be merged

**Comment by 8BallBomBom** [comment]
I could but that wasn't exactly a big change to consider myself being added.

**Comment by gnif** [comment]
It's project policy and our workflow will actually reject the merge if you do not.

**Comment by 8BallBomBom** [comment]
Alrighty 😅

**Comment by 8BallBomBom** [comment]
@gnif Should be golden 😸

**Pull request merged**
